function [tree] = sci_Matrixintro(tree)
// Generated by M2SCI
// Conversion function for Matlab Matrixintro
// Input: tree = Matlab funcall tree
// Ouput: tree = Scilab equivalent for tree

tree=Funcall("exec",1,Rhs(tree.name),tree.lhs)
